name: Workflow con parametros

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Valor env'
        required: false
      dotnet-version-input:
        description: 'Valor de version dotnet'
        required: true
        default: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: extract-version 
    steps:

      - name: 
        run: echo "Version es ${{ needs.extract-version.outputs.app_version }}"

      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ github.event.inputs['dotnet-version-input'] }}  

      - name: Restore 
        run: dotnet restore

      - name: Build 
        run: dotnet build --no-restore --configuration Release